name: Armbian Image Cloud Builder

on:
  workflow_dispatch:
    inputs:
      board:
        description: Target board
        type: choice
        required: true
        options:
          - aml-s9xx-box
          - bananapi
          - bananapim1plus
          - bananapim2
          - bananapim2plus
          - bananapim2ultra
          - bananapim2zero
          - bananapim3
          - bananapim5
          - bananapim64
          - bananapipro
          - bananapir2
          - bananapir2pro
          - beelinkx2
          - clearfogbase
          - clearfogpro
          - clockworkpi-a06
          - cubieboard
          - cubieboard2
          - cubieboard4
          - cubietruck
          - cubietruckplus
          - cubox-i
          - espressobin
          - fe-som-rk3399
          - firefly-rk3399
          - helios4
          - helios64
          - imx7sabre
          - jethubj100
          - jethubj80
          - jetson-nano
          - khadas-edge
          - khadas-vim1
          - khadas-vim2
          - khadas-vim3
          - khadas-vim3l
          - lafrite
          - lamobo-r1
          - lepotato
          - lime-a10
          - lime-a33
          - lime-a64
          - lime
          - lime2
          - macchiatobin-doubleshot
          - melea1000
          - micro
          - microzed
          - miqi
          - mk808c
          - nanopct3
          - nanopct3plus
          - nanopct4
          - nanopi-r1
          - nanopi-r1s-h5
          - nanopi-r2c
          - nanopi-r2s
          - nanopi-r4s
          - nanopia64
          - nanopiair
          - nanopiduo
          - nanopiduo2
          - nanopifire3
          - nanopik1plus
          - nanopik2-s905
          - nanopim1
          - nanopim1plus
          - nanopim1plus2
          - nanopim3
          - nanopim4
          - nanopim4v2
          - nanopineo
          - nanopineo2
          - nanopineo2black
          - nanopineo3
          - nanopineo4
          - nanopineocore2
          - nanopineoplus2
          - odroidc1
          - odroidc2
          - odroidc4
          - odroidhc4
          - odroidm1
          - odroidn2
          - odroidxu4
          - olimex-som-a20
          - olimex-som204-a20
          - olinux-som-a13
          - onecloud
          - orangepi-r1
          - orangepi-r1plus-lts
          - orangepi-r1plus
          - orangepi-rk3399
          - orangepi
          - orangepi2
          - orangepi3-lts
          - orangepi3
          - orangepi4-lts
          - orangepi4
          - orangepilite
          - orangepilite2
          - orangepimini
          - orangepione
          - orangepioneplus
          - orangepipc
          - orangepipc2
          - orangepipcplus
          - orangepiplus
          - orangepiplus2e
          - orangepiprime
          - orangepiwin
          - orangepizero
          - orangepizero2
          - orangepizeroplus
          - orangepizeroplus2-h3
          - orangepizeroplus2-h5
          - pcduino2
          - pcduino3
          - pcduino3nano
          - pine64
          - pine64so
          - pinebook-a64
          - pinebook-pro
          - pinecube
          - pineh64-b
          - pineh64
          - quartz64a
          - radxa-zero
          - radxa-zero2
          - recore
          - renegade
          - rk322x-box
          - rk3318-box
          - roc-rk3399-pc
          - rock-3a
          - rock-5b
          - rock64
          - rockpi-4a
          - rockpi-4b
          - rockpi-4bplus
          - rockpi-4c
          - rockpi-4cplus
          - rockpi-e
          - rockpi-n10
          - rockpi-s
          - rockpro64
          - rpi4b
          - station-m1
          - station-m2
          - station-m3
          - station-p1
          - station-p2
          - sunvell-r69
          - teres-a64
          - tinkerboard-2
          - tinkerboard
          - tritium-h3
          - tritium-h5
          - udoo
          - uefi-arm64
          - uefi-riscv64
          - uefi-x86
          - virtual-qemu
          - xt-q8l-v10
          - z28pro
          - zeropi

      branch:
        description: Kernel and U-Boot branch
        type: choice
        required: false
        default: current
        options:
          - legacy
          - current
          - edge

      release:
        description: Upstream OS release
        type: choice
        required: true
        default: bullseye
        options:
          - buster
          - bullseye
          - sid
          - focal
          - jammy

      build_lib_tag:
        description: Git branch of the armbian/build repo
        type: string
        default: master

      user_patches_repo:
        description: GitHub repo with user patches, "username/repo"; defaults to the current repo.
        type: string

      user_patches_tag:
        description: Git branch of the user patches repo
        type: string

      build_type:
        description: Bare minimum or batteries included?
        type: choice
        required: true
        default: minimal
        options:
          - u-boot
          - kernel
          - minimal
          - default
          - desktop

      bsp_freeze:
        description: Freeze kernel, U-Boot and DTB version
        required: true
        type: boolean
        default: true

      install_headers:
        description: Install kernel headers
        type: boolean
        default: false

      disable_ipv6:
        description: Disable IPv6 support
        type: boolean
        default: true

      rootfs_type:
        description: Root filesystem
        type: choice
        required: true
        default: ext4
        options:
          - ext4
          - f2fs
          - btrfs
          - xfs
          - nfs
          - fel

      btrfs_compression:
        description: Btrfs compression algorithm (and optionally compression level)
        type:

      fixed_image_size:
        description: Create image file of this size (in megabytes) instead of minimal
        type: string

      boot_size:
        description: Size (in megabytes) for separate /boot filesystem; used if rootfs set to non-ext4
        type: string
        default: '96'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout-armbian-build
      name: Checkout the armbian/build repository @ ${{ inputs.build_lib_tag }}
      uses: actions/checkout@v3
      with:
        repository: armbian/build
        ref: ${{ inputs.build_lib_tag }}

    - id: checkout-user-patches
      name: Checkout the user patches @ ${{ inputs.user_patches_tag }}
      uses: actions/checkout@v3
      if: inputs.user_patches_repo
      with:
        repository: ${{ inputs.user_patches_repo }}
        ref: ${{ inputs.user_patches_tag }}
        path: build

    - id: compile
      name: Compile
      run: build/compile.sh
      env:
        BOARD: ${{ inputs.board }}
        BRANCH: ${{ inputs.branch }}
        RELEASE: ${{ inputs.release }}
        UBOOT_ONLY: ${{ inputs.build_type == 'u-boot' && 'yes' }}
        KERNEL_ONLY: ${{ inputs.build_type == 'kernel' && 'yes' }}
        BUILD_MINIMAL: ${{ inputs.build_type == 'minimal' && 'yes' }}
        BUILD_DESKTOP: ${{ inputs.build_type == 'desktop' && 'yes' }}
        KERNEL_CONFIGURE: no  # use user patches
        COMPRESS_OUTPUTIMAGE: yes

    - id: upload
      name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/output
